name = "cf-worker-ws-dev"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
routes = [
  { pattern = "cloud.arrows.biz.id", custom_domain = true },
  { pattern = "quiz.int.vidio.com.cloud.arrows.biz.id", custom_domain = true }
]
workers_dev = true

[vars]
#PROXYIP = "178.128.91.137:443"
#UUID = "7372a1e7-3095-481c-8ce8-c87f4a8daa74"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
