name = "cf-sg"
main = "_worker.js"
compatibility_date = "2023-05-26"
routes = [
  { pattern = "cf.arrows.biz.id", custom_domain = true },
  { pattern = "quiz.int.vidio.com.cf.arrows.biz.id", custom_domain = true }
  { pattern = "quiz.vidio.com.cf.arrows.biz.id", custom_domain = true }
]
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "128.199.218.226:443"
# UUID = "77f82176-8f3d-4163-be41-f8a1416b56dc"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
